server:
  port: ****

# eureka
eureka:
  instance:
    hostname: gmall-netfix-eureka-7001
  client:
    register-with-eureka: false #表示是否像eureka 注册自己
    fetch-registry: false #为 false意思自己是注册中心
    service-url:
      defaultZone:*****